#!/usr/bin/env python3
"""Generate src/myr/my_bidi_mirror_data.h from the local BidiMirroring.txt
(offline; SheenBidi-3.0.0/Tools/Unicode/). UBA L4 (M12b): codepoints in
RTL runs are replaced by their mirror glyph.
"""
import os

AWTK = os.path.expanduser("~/opensource/awtk")
MIRRORING = os.path.join(
    AWTK, "3rd/SheenBidi-3.0.0/Tools/Unicode/BidiMirroring.txt")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "myr",
                   "my_bidi_mirror_data.h")

pairs = []
with open(MIRRORING, encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split(";")]
        left = parts[1].split("#")[0].strip()  # strip trailing comment
        a, b = int(parts[0], 16), int(left, 16)
        pairs.append((a, b))

with open(OUT, "w", encoding="utf-8") as out:
    out.write("""/**
 * @file my_bidi_mirror_data.h
 * @brief GENERATED by tools/gen_bidi_mirror_data.py from the local UCD
 * BidiMirroring.txt (full table, %d pairs). Do not edit by hand.
 *
 * UBA rule L4 (M12b): a codepoint at an RTL embedding level is rendered
 * as its mirror glyph.
 */
#ifndef MY_BIDI_MIRROR_DATA_H
#define MY_BIDI_MIRROR_DATA_H

#include <stdint.h>

typedef struct my_bidi_mirror_t {
  uint32_t cp;
  uint32_t mirror;
} my_bidi_mirror_t;

static const my_bidi_mirror_t MY_BIDI_MIRRORS[] = {
""" % len(pairs))
    for a, b in pairs:
        out.write("    {0x%04Xu, 0x%04Xu},\n" % (a, b))
    out.write("};\n\n#endif /* MY_BIDI_MIRROR_DATA_H */\n")

print("mirrors: %d -> %s" % (len(pairs), OUT))
