#!/usr/bin/env python3
"""Generate src/myr/my_arabic_shape_data.h from local UCD files (offline).

Inputs (both local, no network):
  - ArabicShaping.txt (joining types)   : awtk/tools/data/
  - UnicodeData.txt (presentation forms): SheenBidi-3.0.0/Tools/Unicode/

Output table: per Arabic base codepoint the {isolated, final, initial,
medial} presentation forms (from UnicodeData decomposition mappings whose
name starts with ARABIC), plus joining-type classes for codepoints in the
Arabic-relevant blocks that are not plain non-joining (U).
"""
import os
import sys

AWTK = os.path.expanduser("~/opensource/awtk")
ARABIC_SHAPING = os.path.join(AWTK, "tools/data/ArabicShaping.txt")
UNICODE_DATA = os.path.join(
    AWTK, "3rd/SheenBidi-3.0.0/Tools/Unicode/UnicodeData.txt")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "myr",
                   "my_arabic_shape_data.h")

JOINING = {}  # cp -> 'D'/'R'/'L'/'T'/'C'/'U'
with open(ARABIC_SHAPING, encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split(";")]
        cp = int(parts[0], 16)
        JOINING[cp] = parts[2]

# base cp -> {form: cp}
FORMS = {}
LAM_ALEF = {}  # alef cp -> {form: ligature cp} (M12b)
with open(UNICODE_DATA, encoding="utf-8") as f:
    for line in f:
        parts = line.strip().split(";")
        if len(parts) < 6:
            continue
        cp = int(parts[0], 16)
        name = parts[1]
        decomp = parts[5]
        if not name.startswith("ARABIC") or not decomp.startswith("<"):
            continue
        tag, _, rest = decomp.partition("> ")
        form = tag[1:]
        if form not in ("isolated", "final", "initial", "medial"):
            continue
        cps = rest.split()
        if len(cps) != 1:
            # LamAlef ligatures (M12b): <isolated|final> 0644 062X --
            # only the 4 mandatory Alef variants, not the other
            # "LAM WITH X" ligatures (context-dependent, not mandatory)
            if len(cps) == 2 and int(cps[0], 16) == 0x0644 and \
               name.startswith("ARABIC LIGATURE LAM") and \
               int(cps[1], 16) in (0x0622, 0x0623, 0x0625, 0x0627):
                alef = int(cps[1], 16)
                LAM_ALEF.setdefault(alef, {})[form] = cp
            continue
        base = int(cps[0], 16)
        FORMS.setdefault(base, {})[form] = cp

rows = []
for base in sorted(FORMS):
    forms = FORMS[base]
    rows.append((base, forms.get("isolated", 0), forms.get("final", 0),
                 forms.get("initial", 0), forms.get("medial", 0)))

# joining classes worth storing (non-U) in Arabic-relevant ranges
jrows = [(cp, t) for cp, t in sorted(JOINING.items())
         if t in ("D", "R", "L", "T", "C") and 0x0600 <= cp <= 0x08FF]

JT_ENUM = {"D": "MY_ARABIC_JOIN_DUAL", "R": "MY_ARABIC_JOIN_RIGHT",
           "L": "MY_ARABIC_JOIN_LEFT", "T": "MY_ARABIC_JOIN_TRANSPARENT",
           "C": "MY_ARABIC_JOIN_CAUSING"}

with open(OUT, "w", encoding="utf-8") as out:
    out.write("""/**
 * @file my_arabic_shape_data.h
 * @brief GENERATED by tools/gen_arabic_shape_data.py from local UCD files
 * (ArabicShaping.txt + UnicodeData.txt). Do not edit by hand.
 *
 * Arabic letter joining data: presentation-form mapping (isolated/final/
 * initial/medial) and joining classes for the Arabic blocks.
 */
#ifndef MY_ARABIC_SHAPE_DATA_H
#define MY_ARABIC_SHAPE_DATA_H

#include <stdint.h>

typedef struct my_arabic_form_t {
  uint32_t base;
  uint32_t isolated;
  uint32_t final_;
  uint32_t initial;
  uint32_t medial;
} my_arabic_form_t;

typedef enum my_arabic_join_t {
  MY_ARABIC_JOIN_NONE = 0,   /**< U: does not join */
  MY_ARABIC_JOIN_DUAL,       /**< D: joins both sides */
  MY_ARABIC_JOIN_RIGHT,      /**< R: joins to previous only */
  MY_ARABIC_JOIN_LEFT,       /**< L: joins to next only */
  MY_ARABIC_JOIN_TRANSPARENT,/**< T: marks, skipped for joining */
  MY_ARABIC_JOIN_CAUSING     /**< C: tatweel etc., joins both */
} my_arabic_join_t;

typedef struct my_arabic_join_entry_t {
  uint32_t cp;
  uint8_t join; /**< my_arabic_join_t */
} my_arabic_join_entry_t;

static const my_arabic_form_t MY_ARABIC_FORMS[] = {
""")
    for base, iso, fin, ini, med in rows:
        out.write("    {0x%04Xu, 0x%04Xu, 0x%04Xu, 0x%04Xu, 0x%04Xu},\n"
                  % (base, iso, fin, ini, med))
    out.write("};\n\nstatic const my_arabic_join_entry_t MY_ARABIC_JOINS[] = {\n")
    for cp, t in jrows:
        out.write("    {0x%04Xu, %s},\n" % (cp, JT_ENUM[t]))
    out.write("""};

typedef struct my_arabic_ligature_t {
  uint32_t alef;     /**< U+0622/0623/0625/0627 */
  uint32_t isolated; /**< lam-alef ligature, isolated form */
  uint32_t final_;   /**< lam-alef ligature, final form (joins previous) */
} my_arabic_ligature_t;

/** @brief Lam+Alef mandatory ligatures (M12b). The ligature behaves as a
 * right-joining char (like ALEF): final_ when it joins the previous
 * char, isolated otherwise. */
static const my_arabic_ligature_t MY_ARABIC_LAM_ALEF[] = {
""")
    for alef in sorted(LAM_ALEF):
        lig = LAM_ALEF[alef]
        out.write("    {0x%04Xu, 0x%04Xu, 0x%04Xu},\n"
                  % (alef, lig.get("isolated", 0), lig.get("final", 0)))
    out.write("};\n\n#endif /* MY_ARABIC_SHAPE_DATA_H */\n")

print("forms: %d, joins: %d, lam-alef: %d -> %s"
      % (len(rows), len(jrows), len(LAM_ALEF), OUT))

# print the forms of a few known words for test baking
for word in ("محمد", "سلام"):
    print(word, "->", ["%04X" % ord(c) for c in word])
    for c in word:
        base = ord(c)
        forms = FORMS.get(base, {})
        print("  %04X join=%s iso=%04X fin=%04X ini=%04X med=%04X" % (
            base, JOINING.get(base, "U"),
            forms.get("isolated", 0), forms.get("final", 0),
            forms.get("initial", 0), forms.get("medial", 0)))
