#!/usr/bin/env python3
"""Generate src/myr/my_line_break_data.h from awtk's vendored
libunibreak linebreakdata.c (itself generated from LineBreak-11.0.0.txt;
offline). The UCD classes are mapped to myui's simplified line-break
classes for the text_area word-wrap breaker (M12d).
"""
import os
import re

AWTK = os.path.expanduser("~/opensource/awtk")
SRC = os.path.join(AWTK, "3rd/libunibreak/linebreakdata.c")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "myr",
                   "my_line_break_data.h")

# simplified classes (enum order must match my_line_break.h)
# 0 AL  no break inside a letter/number run
# 1 SP  ascii space: break here, space is consumed
# 2 HY  hyphen/soft break: break AFTER
# 3 ID  ideographic & default: break allowed between
# 4 NS  no-start (closing punct): never starts a visual line
# 5 OP  open bracket: never ends a visual line
# 6 BK  hard break (handled by the physical-line logic, not the table)
MAP = {
    "AL": "AL", "NU": "AL", "HL": "AL", "LE": "AL", "WJ": "AL",
    "ZWJ": "AL", "GL": "AL", "CM": "AL", "QU": "AL", "PR": "AL",
    "SP": "SP",
    "HY": "HY", "BA": "HY",
    "ID": "ID", "AI": "ID", "IN": "ID", "XX": "ID", "SA": "ID",
    "SG": "ID", "RI": "ID", "EB": "ID", "EM": "ID", "ZW": "ID",
    "H2": "ID", "H3": "ID", "JL": "ID", "JV": "ID", "JT": "ID",
    "NS": "NS", "CL": "NS", "CP": "NS", "EX": "NS", "IS": "NS",
    "PO": "NS", "SY": "NS",
    "OP": "OP",
    "BK": "BK", "CR": "BK", "LF": "BK", "NL": "BK", "BB": "AL",
    "B2": "AL", "CB": "ID", "CJ": "NS", "U": "ID",
}

rows = []
pat = re.compile(r"\{\s*(0x[0-9A-Fa-f]+),\s*(0x[0-9A-Fa-f]+),\s*LBP_(\w+)\s*\}")
with open(SRC, encoding="utf-8") as f:
    for line in f:
        m = pat.search(line)
        if not m:
            continue
        lo = int(m.group(1), 16)
        hi = int(m.group(2), 16)
        if m.group(3) == "Undefined":
            continue  # sentinel entry
        cls = MAP[m.group(3)]
        if rows and rows[-1][2] == cls and rows[-1][1] + 1 == lo:
            rows[-1][1] = hi  # merge adjacent same-class intervals
        else:
            rows.append([lo, hi, cls])

with open(OUT, "w", encoding="utf-8") as out:
    out.write("""/**
 * @file my_line_break_data.h
 * @brief GENERATED by tools/gen_line_break_data.py from awtk's vendored
 * libunibreak linebreakdata.c (UCD LineBreak-11.0.0). Do not edit.
 *
 * Interval table (start, end inclusive) of simplified line-break
 * classes; sorted, non-overlapping. Class enum: my_line_break.h.
 */
#ifndef MY_LINE_BREAK_DATA_H
#define MY_LINE_BREAK_DATA_H

#include <stdint.h>

typedef struct my_lb_entry_t {
  uint32_t lo, hi;
  uint8_t cls; /**< my_line_break_class_t */
} my_lb_entry_t;

static const my_lb_entry_t MY_LINE_BREAKS[] = {
""")
    for lo, hi, cls in rows:
        out.write("    {0x%04Xu, 0x%04Xu, MY_LB_%s},\n" % (lo, hi, cls))
    out.write("};\n\n#endif /* MY_LINE_BREAK_DATA_H */\n")

print("entries: %d -> %s" % (len(rows), OUT))
