/**
 * @file gen_bitmap_font.c
 * @brief One-off generator for my_font_bitmap_data.h (built-in 8x8 font).
 *
 * Renders ASCII 32..126 at 8px with a system TTF (Liberation Sans,
 * SIL Open Font License 1.1) via stb_truetype and packs each glyph into
 * 8 bytes (1bpp, MSB-left). Regenerate with:
 *   cc -I 3rd tools/gen_bitmap_font.c -o /tmp/gen_bitmap_font && /tmp/gen_bitmap_font
 * Font source attribution: Liberation Sans (Red Hat, OFL-1.1).
 */
#include <stdio.h>
#include <stdlib.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "stb/stb_truetype.h"

#define FIRST 32
#define LAST 126
#define GLYPH_SIZE 8

int main(void) {
  static const char* CANDIDATES[] = {
      "/usr/share/fonts/liberation-sans-fonts/LiberationSans-Regular.ttf",
      "/usr/share/fonts/truetype/liberation-sans-fonts/LiberationSans-Regular.ttf",
      "/usr/share/fonts/google-droid-sans-fonts/DroidSans.ttf",
  };
  unsigned char* ttf = NULL;
  long size = 0;
  stbtt_fontinfo font;
  unsigned char bitmap[GLYPH_SIZE * GLYPH_SIZE * 2];
  unsigned char packed[LAST - FIRST + 1][GLYPH_SIZE];
  FILE* out;
  int c, i, j, b;
  const char* used = NULL;

  for (i = 0; i < 3 && ttf == NULL; i++) {
    FILE* f = fopen(CANDIDATES[i], "rb");
    if (f != NULL) {
      fseek(f, 0, SEEK_END);
      size = ftell(f);
      fseek(f, 0, SEEK_SET);
      ttf = (unsigned char*)malloc((size_t)size);
      if (ttf != NULL && fread(ttf, 1, (size_t)size, f) != (size_t)size) {
        free(ttf);
        ttf = NULL;
      }
      fclose(f);
      used = CANDIDATES[i];
    }
  }
  if (ttf == NULL || !stbtt_InitFont(&font, ttf, 0)) {
    fprintf(stderr, "gen: no usable TTF found\n");
    return 1;
  }

  for (c = FIRST; c <= LAST; c++) {
    int w, h, xoff, yoff;
    unsigned char* bm = stbtt_GetCodepointBitmap(
        &font, stbtt_ScaleForPixelHeight(&font, GLYPH_SIZE),
        stbtt_ScaleForPixelHeight(&font, GLYPH_SIZE), c, &w, &h, &xoff, &yoff);
    for (i = 0; i < GLYPH_SIZE; i++) {
      packed[c - FIRST][i] = 0;
    }
    for (i = 0; i < h && i < GLYPH_SIZE; i++) {
      unsigned char row = 0;
      for (j = 0; j < w && j < GLYPH_SIZE; j++) {
        if (bm[i * w + j] > 64) { /* low threshold: keep thin 8px strokes */
          row |= (unsigned char)(0x80u >> j);
        }
      }
      packed[c - FIRST][i] = row;
    }
    stbtt_FreeBitmap(bm, NULL);
    (void)bitmap;
  }

  out = fopen("src/myr/my_font_bitmap_data.h", "w");
  if (out == NULL) {
    return 1;
  }
  fprintf(out,
          "/* Generated by tools/gen_bitmap_font.c from %s\n"
          " * (Liberation Sans, SIL Open Font License 1.1). Do not edit.\n"
          " * 95 glyphs, ASCII 32..126, 8x8 1bpp (MSB-left), 8 bytes each.\n"
          " */\n"
          "static const unsigned char MY_FONT_BITMAP_DATA[95][8] = {\n",
          used);
  for (c = FIRST; c <= LAST; c++) {
    fprintf(out, "  {");
    for (b = 0; b < GLYPH_SIZE; b++) {
      fprintf(out, "0x%02X%s", packed[c - FIRST][b], b < 7 ? "," : "");
    }
    fprintf(out, "}, /* 0x%02X '%c' */\n", c, c == FIRST ? ' ' : c);
  }
  fprintf(out, "};\n");
  fclose(out);
  printf("gen: wrote src/myr/my_font_bitmap_data.h from %s\n", used);
  free(ttf);
  return 0;
}
